name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "^18.1"
          cache: "yarn"
      - run: yarn install
      - run: yarn test
      - name: Build package
        run: yarn build
      - name: Publish
        run: npx semantic-release@19.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
